spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}?user=${DB_USER}&password=${DB_PASSWORD}&sslmode=require
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate